[tool.poetry]
name = "todol-archi"
version = "0.1.0"
description = "Todol-archi - laboratoire Python"
authors = ["Sébastien 'doyouDance' Reisen"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
ipython = "9.0.0"
pylint = "3.3.5"
pytest = "8.3.5"
pytest-cov = "6.0.0"
pytest-qt = "4.4.0"
ruff = ">=0.5.3"
coverage = "7.6.12"
rich = "13.9.4"
Pyment = "0.3.3"
pyside6 = "^6.9.0"
pydantic = "^2.11.4"

[tool.poetry.group.dev.dependencies]
loguru = "*"
bandit = "*"
mypy = "*"
black = "*"
sphinx = "*"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = ["tests"]
python_files = "test_*.py"

[tool.pyright]
include = ["src"]
extraPaths = ["src"]
typeCheckingMode = "basic"

[tool.ruff]
target-version = "py312"
exclude = ["tests", "temp"]
fix = true
src = ["src"]
line-length = 88

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true
preview = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
